### ISSUE TITLE
Bodhi metrics page is broken

### ISSUE THREAD

**Issue by mattiaverga** [fedora-infra/bodhi#2966]
Both in staging and production, visiting the Bodhi metrics page throws a 500 Error:
https://bodhi.fedoraproject.org/metrics
`'NoneType' object has no attribute 'groups'`

**Comment by igor-raits** [comment]
@bowlofeggs when could one expect this to be deployed in fedora?

**Comment by bowlofeggs** [comment]
@ignatenkobrain I expect to start working on making a Bodhi 4.0.0 beta this week. Once it is deployed to staging, it will probably take 2-4 weeks to make it to prod (estimate).
