### ISSUE TITLE
AttributeError: module 'hawkey' has no attribute 'Repo'

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#3193]
Some of our tests recently started failing in Rawhide. It seems that the ```hawkey``` API we are using might have changed there, but I haven't investigated it to be sure what the issue is. As an example:

```
______________ TestSanityCheckRepodata.test_comps_invalid_notxml _______________

self = <bodhi.tests.server.test_util.TestSanityCheckRepodata testMethod=test_comps_invalid_notxml>

    def test_comps_invalid_notxml(self):
        """RepodataException should be raised if comps is invalid."""
        comps = os.path.join(self.tempdir, 'comps.xml')
        with open(comps, 'w') as uinfo:
            uinfo.write('this is not even xml')
        base.mkmetadatadir(self.tempdir, comps=comps)
    
        with self.assertRaises(util.RepodataException) as exc:
>           util.sanity_check_repodata(self.tempdir, repo_type='yum')

bodhi/tests/server/test_util.py:488: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    def sanity_check_repodata(myurl, repo_type):
        """
        Sanity check the repodata for a given repository.
    
        Args:
            myurl (basestring): A path to a repodata directory.
            repo_type (str): This should be set to 'yum' for Yum repositories, 'module' for module
                repositories, or 'source' for source repositories.
        Raises:
            Exception: If the repodata is not valid or does not exist.
            ValueError: If repo_type is not an acceptable value.
        """
        if repo_type not in ('module', 'source', 'yum'):
            raise ValueError('repo_type must be one of module, source, or yum.')
    
        h = librepo.Handle()
        h.setopt(librepo.LRO_REPOTYPE, librepo.LR_YUMREPO)
        h.setopt(librepo.LRO_DESTDIR, tempfile.mkdtemp())
    
        if myurl[-1] != '/':
            myurl += '/'
        if myurl.endswith('repodata/'):
            myurl = myurl.replace('repodata/', '')
    
        h.setopt(librepo.LRO_URLS, [myurl])
        h.setopt(librepo.LRO_LOCAL, True)
        h.setopt(librepo.LRO_CHECKSUM, True)
        h.setopt(librepo.LRO_IGNOREMISSING, False)
        r = librepo.Result()
        try:
            h.perform(r)
        except librepo.LibrepoException as e:
            rc, msg, general_msg = e.args
            raise RepodataException(msg)
    
        repo_info = r.getinfo(librepo.LRR_YUM_REPO)
        primary_sack = hawkey.Sack()
>       hk_repo = hawkey.Repo(myurl)
E       AttributeError: module 'hawkey' has no attribute 'Repo'

bodhi/server/util.py:274: AttributeError
```

**Comment by bowlofeggs** [comment]
It seems that this also is causing f29-unit to fail in #3191.

**Comment by bowlofeggs** [comment]
Here is an update to hawkey that might be relevant: https://bodhi.fedoraproject.org/updates/FEDORA-2019-2612a121ba

**Comment by bowlofeggs** [comment]
This seems to be a relevant commit: https://github.com/rpm-software-management/libdnf/commit/d59758ef2323a001c3a93b81b1afd0a2cb4f46d0#diff-b504b0f7c5c777b6477a350942890247

**Comment by bowlofeggs** [comment]
Here is a thread about this issue: https://lists.fedoraproject.org/archives/list/infrastructure@lists.fedoraproject.org/thread/433LMDYOSO76ZOV44FIT2IH6D25YVTJP/

**Comment by bowlofeggs** [comment]
In https://github.com/rpm-software-management/libdnf/commit/3cb6fc1ed891b135a5da09081a2d657bf591860b I see that there is a change in the libdnf tests to use ```libdnf.repo.Repo``` instead of ```hawkey.Repo```. It seems to use some kind of config that the old ```hawkey.Repo``` did not use. 

I attempted to use this API but found that it segfaults if used more than once in the same process: https://github.com/rpm-software-management/libdnf/issues/721 and https://github.com/rpm-software-management/libdnf/issues/722

**Comment by bowlofeggs** [comment]
There is a proposed fix at https://github.com/fedora-infra/bodhi/pull/3198

**Comment by bowlofeggs** [comment]
Closed by #3198.
